### ISSUE TITLE
argument와 parameter

### ISSUE THREAD

**Issue by jongheeyun** [CppKorea/CppCoreGuidelines#10]
argument와 parameter를 어떻게 구분하면 좋을까요?
보통 argument는 인자로 parameter는 매개변수로 번역 하는 것 같습니다.

**Comment by GiyeonBang** [comment]
동의합니다. 가끔 parameter를 인수라고 하시는 분도 있지만 정확한 번역은 아니니꺼요.

**Comment by utilForever** [comment]
Argument는 인자, Parameter는 매개변수로 해석하는 경우가 많습니다.
이에 맞춰 번역할 생각입니다.
