### ISSUE TITLE
[질문] 본 가이드라인은  Gitbook을 통해서 퍼블리싱 되면 어떨까요!?

### ISSUE THREAD

**Issue by sosolo0307** [CppKorea/CppCoreGuidelines#108]
1. 본 가이드라인은  [Gitbook](gitbook.com)을 통해서 퍼블리싱 되면 어떨까요!?
  - 다른곳에 보여지는곳이 없다면 보는데 편할 것 같다는 생각이 들어서 적어 봤습니다.
2. github의 Project 기능을 이용해서 진행상태를 추적하면 어떨까요?
![image](https://cloud.githubusercontent.com/assets/5888757/21483468/b73759fc-cbc5-11e6-9455-721d417c3ad9.png)

**Comment by utilForever** [comment]
안녕하세요, 먼저 좋은 의견을 주셔서 감사하다는 말씀 드립니다.

번역이 완료되면 PDF로 만들 생각이었습니다만, Gitbook으로도 출판하면 좋겠네요.
긍정적으로 검토해 보겠습니다.
얼마 전에 Projects라는 기능이 추가되어서 사용하고 있는 프로젝트가 있습니다.
진행 상태 추적을 위해 작성할 수 있도록 하겠습니다.
