### ISSUE TITLE
Performance : Eliminate redundant indirections??

### ISSUE THREAD

**Issue by sedman** [CppKorea/CppCoreGuidelines#11]
Eliminate redundant indirections

이 문장에서 indirection을 문맥에 맞게 어떻게 해석 해야 될까요?

"간접접근" 은 어떤가요?

**Comment by minjang** [comment]
네, 간접접근 또는 간접참조가 가장 정확한 번역이라고 생각합니다. 그냥 간접접근이라해도 좋다고 봅니다. 불필요한 간접접근 혹은 간접참조를 없애라..

**Comment by utilForever** [comment]
김민장님 의견처럼 "불필요한 간접 접근을 없애라"가 좋은 번역이라고 봅니다.

**Comment by sedman** [comment]
답변 감사합니다!
