### ISSUE TITLE
[질문] 작업 시 변경 할 파일

### ISSUE THREAD

**Issue by jongheeyun** [CppKorea/CppCoreGuidelines#112]
원문이 변경되었거나 추가된 항목, 아직 번역이 안된 부분을 작업하고 있습니다.
CppCoreGuidelines - English.md 와 Subsections 디렉토리의 파일만 수정하면 되나요? 
CppCoreGuidelines - Korean.md까지 3개를 수정해야하나요?

**Comment by utilForever** [comment]
Subsection은 따로 수정하지 않으셔도 괜찮습니다. English와 Korean만 수정하시면 됩니다.

**Comment by jongheeyun** [comment]
예. 감사합니다.
