### ISSUE TITLE
CP: Concurrency and Parallelism 번역 중

### ISSUE THREAD

**Issue by jongheeyun** [CppKorea/CppCoreGuidelines#113]
작업하는 부분을 공유 드립니다.

CP: Concurrency and Parallelism을 번역하고 있습니다.

**Comment by utilForever** [comment]
감사합니다. Subsection에 해당 번역본이 있으니 참고하세요.
https://github.com/CppKorea/CppCoreGuidelines/blob/master/Subsections/CP%20-%20Concurrency%20and%20Parallelism.md
