### ISSUE TITLE
CP - Concurrency and Parallelism 번역해보고자 합니다.

### ISSUE THREAD

**Issue by nochoco-lee** [CppKorea/CppCoreGuidelines#128]
안녕하세요, CP 항목중 빠진 부분들을 제가 번역해보아도 될까요?
아래와 같이 진행해보려 하며 CP.con 부분 먼저 작업 마치게 되면 PR 올리도록 하겠습니다.

https://github.com/nochoco-lee/CppCoreGuidelines/commit/e11ceb88161408561727b89378c54880255e5178

**Comment by luncliff** [comment]
@nochoco-lee 

현재는 `master` 브런치가 아닌 `sync` 브런치를 기준으로 번역작업을 진행하고 있습니다.  
branch생성 및 PR에 유의해주시기 바랍니다. :)

아래 Milestone은 신경쓰지 마시고 작업 하시면서 필요하다고 느끼실 때만 PR을 주시면 됩니다

**Comment by nochoco-lee** [comment]
아 그렇군요, 작업시 참고하도록 하겠습니다. 알려주셔서 감사합니다! :)
