### ISSUE TITLE
SL - The Standard Library 번역

### ISSUE THREAD

**Issue by honggyukim** [CppKorea/CppCoreGuidelines#129]
안녕하세요. SL 섹션을 읽어보다가 (약 30%정도) 일부 번역을 시작해 봤는데 혹시 다른분이 진행하지 않으시면 제가 맡아서 진행해도 괜찮을까요? 아래 이슈에서 말씀해주신대로 `sync` branch 를 대상으로 하겠습니다.

원문: [SL: The Standard Library](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#sl-the-standard-library)

**Comment by luncliff** [comment]
@honggyukim 물론입니다.
branch에서 작업하신걸 보고 있었습니다 :) (스토커?)

아래 Milestone은 신경쓰지 마시고 작업 하시면서 필요하다고 느끼실 때만 PR을 주시면 됩니다

**Comment by honggyukim** [comment]
> branch에서 작업하신걸 보고 있었습니다 :) (스토커?)

지켜보셨다니 부끄럽습니다.. ;;

> 아래 Milestone은 신경쓰지 마시고 작업 하시면서 필요하다고 느끼실 때만 PR을 주시면 됩니다

넵. 금방 마무리를 할 수 있을것 같지는 않지만 시간 나는대로 작업해서 어느정도 완료되면 PR 보내도록 하겠습니다. 감사합니다 :)

**Comment by honggyukim** [comment]
@luncliff 제가 많이 기다리게 해드렸네요.. 죄송합니다.
지금까지 작업한 내용은 #133 에 올려두었습니다. 편하신 시간에 검토 부탁드립니다.

**Comment by luncliff** [comment]
@honggyukim 님, 제가 PR을 합친 이후 ReadMe에 성함을 추가하지 않았더군요. 깜빡해서 죄송합니다 :(
ReadMe에 어떻게 넣어드리면 될까요?

+ 이 이슈는 닫아도 괜찮을지요?

**Comment by honggyukim** [comment]
@luncliff 안녕하세요. 다시 보니 [Stdlib.md](https://github.com/CppKorea/CppCoreGuidelines/blob/sync/sections/Stdlib.md) 라는 파일이 있는데 제가 작성한건 아니지만 삭제해야할지 모르겠네요.. 그리고 원래 문서의 예제 코드는 syntax highlighting 을 하면 더 좋을것 같은데 README 하고 같이 조금 더 수정해서 다시 올려드려도 괜찮을까요?
그리고 내용중에 혹시 수정이 필요한 부분을 알려주시면 같이 업데이트 하도록 하겠습니다.

**Comment by luncliff** [comment]
@honggyukim 물론입니다. 
말씀하신대로 ReadMe에 추가해서 새로 올려주시면 좋을 것 같습니다. :)

**Comment by honggyukim** [comment]
말씀드렸던 내용의 PR 을 #134 에 올려두었습니다. 확인 부탁 드립니다.

**Comment by honggyukim** [comment]
@luncliff 이제 이 issue 는 close 해도 괜찮을 것 같네요. 신경 써 주셔서 감사합니다 :)
