### ISSUE TITLE
Performance : PER.15: Do not allocate on a critical branch  

### ISSUE THREAD

**Issue by sedman** [CppKorea/CppCoreGuidelines#13]
PER.15: Do not allocate on a critical branch  

critical branch를 어떻게 해석해야 할지 궁금합니다.

검색을 해봐도 관련 의미를 찾기가 힘드네요. 본문에도 추가 설명도 없고,

"성능 크리티컬한 부분에서 할당을 하지마라" 정도 될까요?

PS :  question label을 어떻게 add 하는건가요?

**Comment by GiyeonBang** [comment]
branch는 분기를 뜻하는 단어입니다.
제목은 "결정적인(중요한) 분기에서 할당을 하지 말아라"네요.
critical은 임계라는 단어이기도 합니다.
(예를 들어 임계 영역 critical section)

**Comment by utilForever** [comment]
제목만 있고 내용이 없어서 정확하게 해석을 유추할 수는 없습니다만,
"(성능이나 로직 상에서) 중요한 분기문에서 할당하지 마라." 정도로 해석하면 어떨까 싶습니다.

**Comment by sedman** [comment]
답변 감사합니다.

저도 처음에 "분기분에 할당하지 말라"로 해석했었는데,  
구현적으로 "분기문에 할당"란 의미가 와 닿지가 않아서요. 

원문에 내용이 추가된 후 의미를 파악하는게 나을것같네요.
