### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by masterl** [CppKorea/CppCoreGuidelines#137]
Sorry, I don't speak Korean.

I'd just like to point out that you guys forgot to actually link to each section .md file.

Example:
On `sections/ReadMe.md`, someone clicks on the index entry `In: 소개`
It tries to go to the anchor by appending `#S-introduction` to the url.
It should link to the `sections/Introduction.md` file, if I'm not mistaken.

The same goes for other entries.

**Comment by luncliff** [comment]
@masterl Sorry for late answer and appreciate for your opinion. I couldn't use my time enough to this project these months...  
When I breaking down the document, I thought fixing them won't be that hard, but it was quite confusing to track each sections correctly... we will fix that continuously.

**Comment by luncliff** [comment]
I'm going to open a new issue to guide/track fix of the broken links. 
Thank you again for opening the issue :) @masterl
