### ISSUE TITLE
Interface 번역 분리

### ISSUE THREAD

**Issue by utilForever** [CppKorea/CppCoreGuidelines#14]
@bwahn @typeon
두 분께서 Interface 부분을 나눠서 번역하시기로 결정하셨다면,
그렇게 할 수 있도록 처리하겠습니다. 감사합니다.

**Comment by typeon** [comment]
번역작업을 해본 적이 없어서 약간 걱정이 되기는 하지만 후반부 항목부터 진행해보도록 하겠습니다.
작업할 항목 몇개를 정해서 이슈로 등록한 후에 작업이 완료되면 해당 이슈에 대해서 pull request를 날리는 걸로 해 보겠습니다.

**Comment by utilForever** [comment]
@typeon 네, 감사합니다.
