### ISSUE TITLE
문서 요소들을 나타내는 항목들의 번역 단어

### ISSUE THREAD

**Issue by naxxster** [CppKorea/CppCoreGuidelines#18]
제가 작업하면서 만난 것들입니다.
- Reason : 근거
- Note : 참고 사항
- Example : 예
- Example, bad : 잘못된 예
- Enforcement : 시행하기
- Alternative formulation : 다른 공식
- Exception : 예외 사항

각 용어들이 다른 장에서도 많이 쓰일 것 같은데, 어느 정도 통일된 단어를 선택하는 것이 필요할 것 같습니다.

**Comment by utilForever** [comment]
네, 단어를 통일하는 것 역시 중요한 작업입니다.
올려주실 때마다 지속적으로 갱신할 수 있도록 하겠습니다. 감사합니다.
