### ISSUE TITLE
SF6 번역 문의

### ISSUE THREAD

**Issue by naxxster** [CppKorea/CppCoreGuidelines#20]
SF.6: Use using-directives for transition, for foundation libraries (such as std), or within a local scope

여기서 transition 이라는 것이 의미하는 것이 무엇일까요?

**Comment by minjang** [comment]
아직 본문이 없어서 명확하지가 않은데 느낌에는 namespace "전환" 이라는 의미에서 transition이란 단어를 쓴 것 같네요. (그나저나 namespace를 이름공간이라는 우리말을 쓰는지 네임스페이스를 쓰는지 궁금하군요. 전 이름공간이란 단어에 거부감이 없습니다.)

**Comment by typeon** [comment]
이름공간 괜찮네요.

**Comment by utilForever** [comment]
저도 이름공간이라는 이름에 큰 거부감은 없습니다.

**Comment by naxxster** [comment]
transition 의 경우 이름 공간 밖에 있는 요소들을 이름 공간 안으로 넣을 경우 (이름 공간으로 전환할 경우)
중간에 완충 역할로 사용하는 경우를 뜻하는 것 같네요.
namespace 의 경우 이름공간으로 번역 조정했습니다. 번역 레벨에서는 많이 활용되고 있어서 문제없을 것 같네요.
추가로 unnamed (anonymous) namespace 는 익명 이름 공간으로 처리했습니다.
