### ISSUE TITLE
Interface 어디까지 번역하셨는지 궁금한데요.

### ISSUE THREAD

**Issue by typeon** [CppKorea/CppCoreGuidelines#21]
진도를 더 나가야할지 말아야 할지.

개인적으로 자주 commit하는 방식이 다른 사람에게 참여기회를 줄 수 있고 프로젝트가 살아 있다는 느낌을 줄 수가 있어서 선호하는 편인데, 여기는 pull request가 거의 없어서 꼭지를 맡은 분들이 번역작업을 진행중인지 어떤지 알 수가 없고, 큰 꼭지들의 양이 상당해서 혼자 하기에는 분명히 벅찰거라 생각이 드는데 번역작업을 다한 후에 pull request를 하려는건지 잘 모르겠네요. 진행상황이나 현재 작업상태를 모르면 함께 나눠서 할 수가 없잖아요.

**Comment by utilForever** [comment]
안녕하세요, 의견 감사합니다.
아직 번역 담당자가 지정되지 않은 부분도 있으니 그쪽을 맡아주셔도 괜찮고, 아니면 기존과 같이 밑에서부터 올라오면서 번역을 하는 것도 괜찮을 듯 싶습니다.

**Comment by bwahn** [comment]
@typeon 님, 제가 Interface를 맡아서 하려고 했는데, 다른 일로 진행이 안되네요. 밑에서 부터 번역해서 올라와셔도 좋구요. 전부 맡아서 해주셔도 될 것 같습니다.

**Comment by typeon** [comment]
@bwahn 지금 에러 핸들링 하고 있는데 나중에 interface 진행하겠습니다. 한 부분까지만 commit 잘 해 주시면 쫑나지는 않을 겁니다.
