### ISSUE TITLE
include 라는 용어가 #include 를 하는 행위를 표현할 때

### ISSUE THREAD

**Issue by naxxster** [CppKorea/CppCoreGuidelines#23]
Include `.h` files before other declarations in a file

이런 경우나

Including entities subject to the one-definition rule leads to linkage errors.

이런 경우를 보게 되면

include 라는 것이 #include 를 이용하는 것을 가리키는 것으로 보입니다.
이럴 때 어떻게 번역하는 게 좋을까요?
단순히 포함한다고 쓰면 내용이 제대로 전달이 안 될 것 같고,
인클루드한다라고 쓰면 아예 번역을 안 한 것 같고,
# include 라고 하면 좀 너무 코드같은 느낌이 드는 것 같아서

다 조금씩 마음에 안 드네요.

**Comment by typeon** [comment]
저는 concept이 그런 경우던데 reserved keyword는 영어를 그대로 써주는게 나을지도 모르겠다는 생각이 들었습니다.

**Comment by GiyeonBang** [comment]
제 의견은 reserved keyword 중에서 "#이 안 붙은(전처리기의 의미가 아닌)" include는 포함하라는 뜻이 있으므로  포함한다로 번역하되, 번역하는 단어 중 한국어와 영어 단어 둘 다 쓰이는 단어는 단어(word)이런 식이로 번역하는 것도 좋을 것 같습니다.

**Comment by utilForever** [comment]
저는 방기연님의 의견과 비슷한 생각을 갖고 있습니다. Include에는 포함하다라는 뜻이 있고, #이 붙은 Include의 의미도 포함한다는 겁니다. '파일에서 다른 선언을 하기 전에 헤더 파일(.h)를 포함하라'라고 해석하면 어떨까 싶습니다.
