### ISSUE TITLE
문서 NL - Naming and layout rules.md의 번역에 대해서...

### ISSUE THREAD

**Issue by GiyeonBang** [CppKorea/CppCoreGuidelines#28]
안녕하세요.
원래 NL 번역을 맡기로 예약한 방기연입니다.
우선 미리 번역해주신 분께 감사를 드립니다.
또한 개인적인 일(중간고사) + 다른 문서 번역으로 인해 번역이 늦어진 점도 사과드립니다.
저는 NL 초안에 대해 개선 작업을 하고자 합니다.
문맥에 맞지 않거나 의역된 부분을 수정하고 있으며 조금 더 원본에 가깝게 직역하고자 합니다.
번역해주신 문서 수정에 양해를 구합니다.

**Comment by typeon** [comment]
양해를 구하다니요. 수정해야 번역글이 더 좋아지죠.
더 보기 좋게 잘해주세요.

**Comment by utilForever** [comment]
언제나 수고 많으십니다. 감사합니다.
