### ISSUE TITLE
inline을 동사화하여 inlined 라고 할 경우

### ISSUE THREAD

**Issue by jongheeyun** [CppKorea/CppCoreGuidelines#32]
inline function은 그대로 인라인 함수라고 번역하면 될 것 같습니다.
그런데 inline을 동사화해서 inlined 라고 하면 어떻게 번역하는 것이 좋을까요?
"functions are easily inlined..."
"내제화하다", "내제시키다", "즉시 처리하게 하다"... 뭘로 해도 어색하고 어감이 와 닿지 않네요.

좋은 단어 있을까요?

**Comment by typeon** [comment]
functions are easily inlined.. - 쉽게 인라인 함수화할 수 있다. 쉽게 인라인 함수로 만들 수 있다.

**Comment by GiyeonBang** [comment]
인라인된.. (인라인이 적용된)이 좋지 않을까요?
함수들은 쉽게 인라인(이 적용) 될 수 있다.

**Comment by GiyeonBang** [comment]
음... 인라인은 엄연히 지정자(specifier)이니 인라인이 지정된이 더 좋겠네요.
함수들은 쉽게 인라인이 지정될 수 있다.

**Comment by utilForever** [comment]
함수가 인라인 함수로 변환되는 동작이므로, "함수들이 인라인 함수로 쉽게 변환된다." 정도로 번역하면 어떨까 싶습니다.
