### ISSUE TITLE
[제안] Lifetimes I and II, Introduction to type and resource safety 문서 번역

### ISSUE THREAD

**Issue by utilForever** [CppKorea/CppCoreGuidelines#35]
C++ 핵심 가이드라인에는 Lifetimes I and II와 Introduction to type and resource safety라는 문서가 있습니다. 혹시 이 두 문서를 저랑 같이 번역하실 분이 있다면 댓글로 참여 의사를 남겨주시면 감사하겠습니다. 많은 인원은 필요 없을 듯 하고 2~3명 정도면 충분할 것 같습니다.

**Comment by GiyeonBang** [comment]
저요. NL 끝나는데로 (이번 주 안에 완료) C와 동시에 하려고요.
