### ISSUE TITLE
isocpp에 추가된 docs들 추가 번역

### ISSUE THREAD

**Issue by jen6** [CppKorea/CppCoreGuidelines#4]
https://github.com/isocpp/CppCoreGuidelines/tree/master/docs
가이드 라인 말고도 최근 docs에 cpp관련 문서들이 추가되고 있는데요
Introduction to type and resource safety 이문서 내용이 좋은것 같은데
추가적인 문서에 대한 번역은 진행을 어떻게 해야할까요

**Comment by utilForever** [comment]
문서 번역도 진행할 예정입니다.
업데이트 후에 Issues에 공지사항으로 올릴 수 있도록 하겠습니다.
