### ISSUE TITLE
[참고] 번역 진행 부분 정리

### ISSUE THREAD

**Issue by utilForever** [CppKorea/CppCoreGuidelines#47]
ES : @yiatom 님이 맡고 계십니다.
C - @jenix21 님이 C50까지, C51부터는 김준성님이 맡고 계십니다.

**Comment by typeon** [comment]
T: Template and Generic programming 뒤에서 부터 시작합니다.

**Comment by drvoss** [comment]
혹시 번역 진행 중이신분중에 같이 진행하실 분 계신가요? 저장하려고 보니 이미 다른분이 번역을...

**Comment by drvoss** [comment]
일단 reference 가 빈것 같아 초안을 커밋했어요~

**Comment by utilForever** [comment]
@drvoss 네, 알겠습니다.

**Comment by kangic** [comment]
Resource Management 다른 분께서 앞 부분 올려주셔서 R.20부터 진행하고 있습니다.

**Comment by luncliff** [comment]
안녕하세요! 
C.Copy and Move : C.60 ~ 의 내용과 
To-Do List 를 맡아 번역하고자 합니다. 
이전에 작업파트를 나눈 이슈들을 확인중인데, 혹시 따로 작업중이신 분이 계신가요?

**Comment by utilForever** [comment]
@luncliff 원래 맡아주신 분이 계신데, 연락해 보겠습니다. 확인해보고 댓글 다시 달아드리겠습니다.

**Comment by blackscomber** [comment]
현재 번역 책임자 없는 부분이 어느 부분인지 알고 싶습니다. 저는 담당자가 없는 부분이면 어느쪽이라도 상관없습니다.

**Comment by utilForever** [comment]
아마 진행 상황을 보시면 참고가 되실 듯 합니다.

**Comment by blackscomber** [comment]
R.2 와 R.3 를 해보고 싶습니다. 혹시 담당하고 계신분이 있으시면 말씀해주세요.

**Comment by HIPERCUBE** [comment]
CP 부분이 11월 11일 이후로 진행이 안되고 있는것 같습니다.
제가 담당해서 진행해도 될까요?

**Comment by minjang** [comment]
@HIPERCUBE 안녕하세요. CP 부분의 원문이 아직 너무 완성이 안 되어서 일부러 안 하고 있습니다. 추후에 원문에 좀 더 업데이트 되면 그 때 하려고 합니다. 또 문제점은 원문이 자주 바뀝니다. 그래서 번역을 하더라도 다시 고쳐야 하는 문제가 있습니다.

이게 최신 영문 원본인데요.
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#S-concurrency
우리 저장소에 있는 영어 원문은 4개월 전 것이라 반영이 안 되었습니다.
https://github.com/CppKorea/CppCoreGuidelines/blob/master/CppCoreGuidelines%20-%20English.md#S-concurrency

참고로.. 지금 한글판 저장소에 있는 영어 원문이 약 4개월간 업데이트가 안 되었습니다. 주기적으로 업데이트를 해야 합니다.

혹시나 관심있으시면 먼저 번역해주시고 제가 검토해 드릴 수도 있습니다. 환영합니다 :)

**Comment by utilForever** [comment]
안녕하세요, 김민장님 말씀대로 업데이트 안 한 지가 꽤 된 듯 합니다.
이번주 중으로 원본 내용 확인해서 갱신할 수 있도록 하겠습니다.
언급해주신 @minjang 님께 감사드립니다.

**Comment by kimkj2017** [comment]
SF 문서에서 번역이 매끄럽지 않은 부분을 다듬고 번역이 안 된 부분에 대해서 번역을 진행해도 될까요? https://github.com/CppKorea/CppCoreGuidelines/blob/master/Subsections/SF%20-%20Source%20files.md

**Comment by utilForever** [comment]
@kimkj2013 네, 하셔도 됩니다. :)
