### ISSUE TITLE
번역할 문서 스타일에 대해서

### ISSUE THREAD

**Issue by GiyeonBang** [CppKorea/CppCoreGuidelines#5]
저는 아래와 같은 스타일로 편집하고 있습니다.
### 코드

**원문:**
syntax highlight가 적용되지 않았습니다.
코드가 밋밋하게 보입니다.

```
std::cout << "Hello, World!" << endl;
```

**제안:**
다음과 같은 Markdown을 사용하여 syntax highlight를 주었습니다.

**C++ 코드 Markdown**

``````
```C++
std::cout << "Hello, World!" << endl;
``` 
``````

**Markdown이 적용된 결과**

``` C++
std::cout << "Hello, World!" << endl;
```
### 번역

`>`를 사용하여 번역문 밑에 원문을 넣었습니다.
**원문**:
The answer is 42.

**번역한 문서**:
답은 42.

> The answer is 42.
### 단어, 어휘:
- C++은 C Plus Plus이므로 뒤에 조사는 를, 는과 같은 조사를 붙입니다.
- 번역한 단어
- **T**:
  - type: 형

**Comment by utilForever** [comment]
코드에 Markdown을 쓰면 Syntax Highlight를 줄 수 있다는 장점이 있습니다.
하지만 번역을 하실 때에는 사용하지 않고 해주시기 바랍니다.
원문이 자주 바뀌기 때문에 Markdown을 사용하지 않아야 비교할 때 편합니다.
최종 버전으로 올릴 때에는 Markdown 문법을 사용할 수 있도록 하겠습니다.
의견 감사합니다.
