### ISSUE TITLE
Enforcement 번역에 대한 의견입니다

### ISSUE THREAD

**Issue by drllr** [CppKorea/CppCoreGuidelines#52]
어휘정리 이슈에 댓글로 달았는데, 어휘 의견은 이슈를 등록하라는 가이드를 보고 옮겼습니다:

저는 `Enforcement:` 를 `강조사항:` 으로 번역했습니다. 번역하면서 고민이 가장 많았던 단어였는데요. 이 단어는 Minjang님이 말씀 하신 Police Enforcement와 같은 '집행, 시행, 강제'의 뉘앙스를 담는 경우가 많지만 Cpp Core guidelines 에서는 '강조'의 의미로 사용 했습니다. 좀 낯설긴 하지만, 네이버 영어사전을 검색해보면 3번 뜻으로 나오니 근거없는 용법은 아닙니다.

항목의 내용도 Flag that으로 기술되었습니다. 직역하면 '깃발로 마크하라' 쯤이 되며, 원래의 의미를 담아 의역하면 '꼭 기억해두어라' 쯤이 되는 것 같습니다. (이런 경우에 일반적으로 사용하는 Note that 보다 훨씬 더 강한 어조입니다.) 종합해보면 `Enforcement:`는 `Note:` 항목보다 더 강력히 제안하는 가이드라인이라고 보면 될 것 같고, 저는 영한사전의 용례를 따라 강조사항으로 번역했습니다.

**Comment by jenix21** [comment]
저는 '시행하기'가 적절해 보이는데요.

`Enforcement` 의 사전적인 의미도 중요하지만,
C 섹선에서 제가본 `Enforcement` 의 내용들은 `어떻게 해보라`는 식의 것들이 많아서, 앞서 언급한 가이드라인을 실천하는데 시작점을 제시해주는 것 처럼 보였습니다.

**Comment by drllr** [comment]
좋은 의견 감사합니다. jenix21 님의 댓글보고 Introductions 까지 리뷰해보니 '시행하기'의 의미에 더 가까운 것 같군요. 제 섹션만 번역하다보니 전체적인 쓰임을 몰랐던 것 같네요. 이 이슈는 클로즈하도록 하겠습니다.

**Comment by typeon** [comment]
flag that -> ~이라면 표시한다. 라고 번역했는데, IDE보면 경고, 에러, 중요 위치 등은 플래그 마크로 표시해 두잖아요. 그런 의미로 봤습니다.
