### ISSUE TITLE
[문의] Invariant, Regular Type

### ISSUE THREAD

**Issue by utilForever** [CppKorea/CppCoreGuidelines#53]
@jenix21 댓글로 적어주시기 바랍니다.

**Comment by jenix21** [comment]
wiki 용어에 넣어두긴 했습니다만,
https://github.com/CppKorea/CppCoreGuidelines/wiki/%EB%8B%A8%EC%96%B4,-%EC%96%B4%ED%9C%98-%EC%A0%95%EB%A6%AC

Invariant, Regular Type 두 용어를 어떻게 번역하면 좋을까요.

Invariant 는 클래스의 논리적인 상태들을 의미하고, 이런 상태들은 모델링한 클래스에 한정적이기 때문에 유한적이라는 의미도 있어 보입니다.

Regular Type 은 우선 규칙적인 타입으로 정의 했는데 이상한것 같고, '정규 타입' 으로도 생각해봤습니다.
내장 타입들 처럼 동작하는 사용자 정의 타입이라고 합니다. http://www.stepanovpapers.com/DeSt98.pdf

**Comment by typeon** [comment]
These sections are not orthogonal.
대체 orthogonal이 무슨 뜻으로 쓰이는 겁니까?

**Comment by jenix21** [comment]
@typeon 
orthogonal 은 두개가 서로 겹치지 않는다는 의미로 보시면 될 것 같은데요.
이 섹션들은 겹치는 부분이 있을 수 있다 정도로 보면 어떨까요.

**Comment by typeon** [comment]
@jenix21 아~ 교차하지 않는다는 그런 뜻이군요.

**Comment by utilForever** [comment]
orthogonal은 원래 '수직하는'이라는 뜻으로 수학에서 많이 쓰는 단어입니다.
하지만 여기서는 문맥 상 '어떤 두 사물 또는 두 개념이 상호간에 관계없이 독립적으로 존재하는 것'으로 해석하면 될 것 같습니다.

**Comment by minjang** [comment]
Invariant는 '불변항'이라는 용어로 널리 쓰이지 않나요? 저는 학교에서 그렇게 배워서요. 문맥으로 봐서도 불변항이 맞네요.

Orthogonal은 '직교'라는 의미이고, 직교하는 두 벡터의 내적이 0이라는 뜻에서 어떤 두 개가 직교 한다는 소리는 서로 무관하다라고 해석하시면 됩니다.

Regular type은 문맥에서 보면 "That means roughly behaves like an int"이듯이 int와 같은 형을 'regular' 형이라고 칭했는데요. 보통 C++ 표준에서 이런 인테그럴 타입을 fundamental types이라고 부릅니다. 규칙적인 타입이라는 뜻 보다는 '기본 형' 정도로 해석하는게 무난하지 않나 생각합니다.

http://en.cppreference.com/w/cpp/language/type

**Comment by typeon** [comment]
불변항이 무슨 뜻이죠? 더 이상한데.
예를 들어, 0 이상인 값을 가진 포인트에서 Point(-1,-1)은 오류이라고 판단하는 _0 이상인 값_ 조건을 invariant라고 하는데요.
그래서 이런 조건들은 값변경이 필요한 모든 곳에서 체크해야 하는 것이고,
어떤 언어들은 invariant keyword를 지원하기도 합니다.

**Comment by minjang** [comment]
https://en.wikipedia.org/wiki/Invariant_(computer_science)
https://ja.wikipedia.org/wiki/%E4%B8%8D%E5%A4%89%E6%9D%A1%E4%BB%B6

Invariant, 불변항, 불변조건은 말 그대로 변하지 않아야 하는 식, 항, 조건이라는 뜻입니다. '항'은 다항식의 그 항입니다.

'불변조건'이면 보다 명확할 것 같습니다. 참고로 일본어/중국어도 그렇게 쓰고 있습니다. '불변항'이라는 표현은 수학 분야에서는 쓰입니다.

**Comment by typeon** [comment]
'불변조건'이면 무난해 보이네요. '클래스 불변조건'

**Comment by jenix21** [comment]
regular type 은 primitive(fundamental) type 처럼 동작 하지만 '사용자 정의 타입' 이라는 점에서 약간 다른 뉘앙스를 갖는 단어인 "regular" 를 사용한 것 같은데요. 기본형이라고 번역하면 읽는 사람은 primitive type 으로 이해 할 수도 있을 것 같네요. ㅜ.ㅜ

invariant 도 한글로 번역하기 까다롭네요.
의견 주신대로 '불변조건'으로 정리하겠습니다.

감사합니다. ^^
