### ISSUE TITLE
[필독] 번역 스타일

### ISSUE THREAD

**Issue by utilForever** [CppKorea/CppCoreGuidelines#6]
1. 코드에 Markdown 문법을 적용하지 않습니다.
   원문이 자주 바뀌기 때문에 Markdown을 사용하지 않아야 비교할 때 편합니다. 번역이 어느 정도 진행되어 합치게 되면 그 때 Markdown 문법으로 변환해 Syntax Highlighting을 할 예정입니다. 
2. `>`를 사용해 번역문 밑에 원문을 넣습니다.
   **원문**:
   The answer is 42.
   **번역한 문서**:
   답은 42다.
   
   > The answer is 42.
3. 단어, 어휘는 다른 글을 통해 정리할 예정입니다.

**Comment by bwahn** [comment]
문의하려고, branch를 만들었습니다. https://github.com/CppKorea/CppCoreGuidelines/blob/bwahn-patch-1/Subsections/I%20-%20Interfaces.md 를 보시면, ">인터페이스" 라고 적어보았습니다. 이런식으로 하는거죠?

**Comment by utilForever** [comment]
@bwahn 번역문이 아닌 원문을 인용구로 표시해주시기 바랍니다.

**Comment by bwahn** [comment]
@utilForever  네,

**Comment by bwahn** [comment]
수정을 해보았는데, 맞게 된건지요?

**Comment by utilForever** [comment]
@bwahn 제목은 원문을 안넣으셔도 됩니다.

**Comment by naxxster** [comment]
번역문을 먼저 넣고 원문을 인용구로 넣었더니 diff 를 볼 때 너무 햇갈리는군요.
번역문 아래에 원문을 두는 것이 일반적으로 더 편하지 않을까 생각되는데
원문을 아래쪽에 인용구 처리하는 이유는 뭔가요?

**Comment by utilForever** [comment]
@naxxster 원문은 참고용으로 보기 때문에 인용구로 표시하는 방법을 택했습니다만, diff를 볼 때 헷갈릴 수 있다는 점을 고려하지 않았었네요. 참고하겠습니다.
편집을 하실 때는 인용구를 빼고 하셔도 되겠습니다. 차후에 추가하겠습니다.
