### ISSUE TITLE
[어휘] dangling pointer

### ISSUE THREAD

**Issue by jongheeyun** [CppKorea/CppCoreGuidelines#68]
안녕하세요.

dangling pointer는 어떻게 번역하면 좋을까요.
지금까지 생각해본건 '허상 포인터' 입니다. 허상이 흔히 쓰이는 단어는 아니것 같아서 좀 어색한 느낌도 있습니다.
발음나는대로 '댕글링 포인터'가 의미상 더 와닿지 않을까하는 생각도 듭니다.

**Comment by utilForever** [comment]
저도 '댕글링 포인터'로 적는게 의미상 나아보입니다.

**Comment by sedman** [comment]
저도 댕글링 한표입니다
2015. 11. 17. 오전 12:23에 "Chris Ohk" notifications@github.com님이 작성:

**Comment by DevStarSJ** [comment]
허상 포인트도 나쁘지 않은 표현 같습니다. 아직까진 댕글링 포인터가 더 직관적으로 보이긴 하지만, 장기적으로 해당 단어에 대한 한글표현법을 고려한다면 허상 포인트 1표입니다.

**Comment by GiyeonBang** [comment]
@DevStarSJ 동의합니다. 저도 EMC++ 스터디 중에 허상(의) 포인터로 번역한 적이 있습니다.
일본에서도 그렇게 번역하는 모양입니다.

**Comment by sedman** [comment]
근데 허상포인터라고 하면 뭐지?  하고 잠시 동안 생각하고 찾아볼것 같습니다 댕글링이 친숙하니까요 (저만그런가요??^^;;)   처음
단어가 나올때 "허상포인터(dangling pointer)" 정도로 표기해주는것도
괜찮을것 같습니다
2015. 11. 17. 오후 7:20에 "Giyeon Bang" notifications@github.com님이 작성:

**Comment by utilForever** [comment]
댕글링 포인터와 허상 포인터를 같이 표시하는 것은 어떨지요

**Comment by jongheeyun** [comment]
말씀하신것 처럼 "허상(댕글링) 포인터"로 표현하는것도 좋은 것 같습니다.
