### ISSUE TITLE
[중요] 단어, 어휘 정리

### ISSUE THREAD

**Issue by utilForever** [CppKorea/CppCoreGuidelines#7]
자주 사용하는 단어나 어휘에 대해서 정리합니다.
<B>혹시 단어나 어휘 선택에 관련된 문의가 있다면, 댓글이 아닌 Issues에 등록해주시기 바랍니다.</B>

Argument : 인자
Parameter : 매개변수
Reason : 근거
Note : 참고 사항
Example : 예
Example, bad : 잘못된 예
Enforcement : 시행하기
Alternative formulation : 다른 공식
Exception : 예외 사항

**Comment by typeon** [comment]
위키로 정리하시면 좋을 듯 하네요.

**Comment by utilForever** [comment]
@typeon 의견 감사합니다. 곧 등록하겠습니다.

**Comment by minjang** [comment]
Enforcement가 시행하기로 번역하는 건 좀 어색하지 않나 생각합니다. Enforcement는 가이드라인에서 말하는 내용이 지켜졌는가 살펴보는 것입니다. 그래서 시행이라기 보다는 확인하기, 검열하기, 단속하기, 뭐 이런 단어가 떠오르는데 매끄러운 한국어 단어는 좀 더 고민해봐야겠네요.

(우리나라 고속도로에서 교통단속을 police enforcement가 있다고 합니다.)

**Comment by yiatom** [comment]
저는 `Enforcement` 를 `강조사항` 으로 번역했습니다. 번역하면서 고민이 가장 많았던 단어였는데요. 이 단어는 Minjang님이 말씀 하신 Police Enforcement와 같은 '집행, 시행, 강제'의 뉘앙스를 담는 경우가 많지만 Cpp Core guidelines 에서는 '강조'의 의미로 사용 했습니다. 좀 낯설긴 하지만, 네이버 영어사전을 검색해보면 3번 뜻으로 나오니 근거없는 용법은 아닙니다.

항목의 내용도 Flag that으로 기술되었습니다. 직역하면 '깃발로 마크하라' 쯤이 되며, 일반적으로 사용하는 Note that 보다 훨씬 더 강한 어조입니다. 종합해보면 `Enforcement:`는 `Note:` 항목보다 더 강력히 제안하는 가이드라인이라고 보면 될 것 같습니다.

**Comment by luncliff** [comment]
이번 Pull request에 용어 대역표에 대한 제안을 같이 올렸습니다. 
다른 번역자 분들의 여러 제안을 부탁드립니다.
[용어 대역표 제안](https://github.com/luncliff/CppCoreGuidelines/wiki/%EC%9A%A9%EC%96%B4-%EB%8C%80%EC%97%AD%ED%91%9C)
