### ISSUE TITLE
[어휘] raw pointer

### ISSUE THREAD

**Issue by jongheeyun** [CppKorea/CppCoreGuidelines#88]
안녕하세요.

raw pointer라는 단어가 있습니다. 
smart pointer에 대비되는 단어입니다.
날-포인터..
비스마트 포인터.. 
그냥.. 포인터

스마트 포인터냐 아니냐만 놓고 보면 수식어 없이 '포인터'로 하는게 맞을 것 같기도 합니다.

원문: "Warn if a raw pointer is dereferenced without being tested against `nullptr` (or equivalent) within a function..."

다른 의견 있으신가요?

즐거운 하루 보내세요.

**Comment by luncliff** [comment]
수식어 없이 _일반 포인터_로 기술하면 어떨까요? 그냥 _포인터_도 별 문제가 없을 것 같습니다.

**Comment by GiyeonBang** [comment]
raw data는 미가공 데이터로 쓰이니
원래, 원본, 원초 등의 뜻과
가공되지 않은(미가공된), 생생한, 날 것 등의 뜻을 고려하면 (가공 전의) 원 포인터는 어떤가요?

**Comment by naxxster** [comment]
원시 포인터는 어떨까요?
원시가 한자어이긴한데. 의미적으로 잘 맞는 것 같습니다.

**Comment by GiyeonBang** [comment]
@naxxster 원X가 생각이 안 나서 해매다 드디어 기억났네요 ㅋㅋㅋ

**Comment by GiyeonBang** [comment]
저도 원시 포인터에 찬성이요.

**Comment by minjang** [comment]
저는 '날' 포인터에 한 표입니다.

일단 그냥 '포인터'는 raw/smart 포인터 둘을 모두 포함하는 의미로 쓰이므로 혼동을 줄 소지가 있습니다. 원시 포인터는 raw 보다는 primitive 라는 영어 단어가 먼저 떠 오릅니다. 원본/원래도 raw 보다는 orignal가 생각 납니다. "날 것"이라는 표현은 흔히 쓰므로 날이라는 접두어가 그렇게 어색하지도 않다고 봅니다. 무엇보다 단어도 한 글자라서 경제적입니다.

**Comment by DevStarSJ** [comment]
날 포인터가 더 직관적으로 보이네요.
이미 번역된 책들 보면 대부분 원시 포인터 라 번역을 한 것 같은데...
어떤게 읽는 사람들에게 더 편하게 읽힐지가....
그냥 저도 짧은 거에 한표요. `날` ^_^

**Comment by naxxster** [comment]
좀 더 찾아보니 생짜 포인터라는 말도 쓸 수 있겠네요.
생짜라는 말이 국어사전에 있더군요.

**Comment by minjang** [comment]
네, raw를 날, 생으로 번역하는게 흔하죠. 生 포인터... 그런데 너무 먹음직스럽네요 ㅎㅎ

**Comment by jenix21** [comment]
날 포인터는 스마트 포인터를 똑똑한 포인터로 번역한 것과 비슷해 보이네요. ㅎㅎ
'저수준 포인터'는 어떤가요.

**Comment by minjang** [comment]
보통 한국어 번역을 보면 사람들이 결국 영어 단어를 유추하게 되는데요. 저는 이러한 점에서 raw를 기존 한국어 번역과 충돌되지 않는 선에서 찾고 싶습니다. 예를 들어, 저수준은 low-level, 원시는 primitive, 원/원본은 original을 연상케 해서 바로 raw를 떠올리기 어렵지 않나 생각합니다.

스마트 포인터에서 스마트는 이미 너무 익숙한 영어 단어라 써도 괜찮다고 봅니다. 안타깝게도 raw는 흔히 쓰이는 영어 단어가 아니라 발음 그대로 적기도 애매합니다. 로우로 쓰자면 low가 연상되고, 로로 쓰면 law가 연상되고, 그렇다고 발음대로 뤄로 쓰면 아무도 못 알아 볼 것 같고 쉽지가 않네요.

그래서 결론은 다시 한번 날.. 포인터에 한 표입니다.

**Comment by kangic** [comment]
저는 minjang님 의견처럼 '날 포인터'에 한 표 던집니다. raw data하면 (어떤 처리되지 않은) 날 것의 데이터라는 의미로 많이들 받아들이기 때문에 '날'로 해석되어지는게 직관적으로 이해하기 좋은 것 같습니다.

저도 이걸로 고민을 좀 했었는데 마땅한 대안이 떠오르지 않아 '원형'(원 모양이다라는 측면에서..)이라고 번역을 했는데 fix되면 해당 내용으로 수정해야겠네요.

**Comment by jongheeyun** [comment]
날 포인터가 처음에는 어색했는데 계속 읽어보니 괜찮은 표현이라는 생각이 듭니다.
그러다가 문득, .. "널 포인터.. 날 포인터.. 널 포인터.. 날 포인터.. 널 포인터"
널 포인터의 오타로 오해 하는건 아니겠지. 하는 생각이 들었습니다. ^^;;
그래도 여러 단어 중에서는 "날 포인터"가 적당해 보입니다.

**Comment by rinechran** [comment]
'기존 포인터'가 더 좋을거같은데요
날 포인터 같은경우에는 원서를 안본 사람이 보기에는 이해가 안될거같은데요

**Comment by jongheeyun** [comment]
원문: "Warn if a raw pointer is dereferenced without being tested against nullptr (or equivalent) within a function..."

이 문장은 스마트 포인터가 아닌 포인터를 설명하고 있습니다.
한 단어로 표현하는 것도 좋지만 문장의 의미가 전달 될 수 있도록 "스마트 포인터가 아닌 일반 포인터"라고 풀어서 설명하는게 의미전달에는 오해없이 정확할 것 같다는 생각도 듭니다.

**Comment by Ssangwoo** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

thstkddn1@naver.com 님께 보내신 메일 <Re: [CppCoreGuidelines] [어휘] raw pointer (#88)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by rinechran** [comment]
일반 포인터 좋다고 생각합니다.

**Comment by utilForever** [comment]
기존 번역서에서는 원시 포인터라는 말을 많이 사용합니다.
그런데 우리가 스마트 포인터가 아닌 기존에 사용하던 포인터가 "원시"의 의미를 갖고 있는지에 대해서는 의문이 많이 듭니다. 그냥 포인터를 쓰고 있다가 더 편한 스마트 포인터가 나온 것이니까요.
'날' 포인터도 같은 맥락에서 의문이 들고, 일반 포인터가 문맥상으로는 조금 더 어울리지 않나 생각합니다.

**Comment by minjang** [comment]
"그냥 포인터를 쓰다가 편한 스마트 포인터가 나왔다"는 맥락에서는 오히려 날 포인터가 의미가 있지 않을까요?

일반 포인터도 생각을 해봤는데 제 생각에는 다음의 문제점이 떠오릅니다.

(1) 앞서 제 의견대로 결국 영어 단어로 매핑이 직관적어야 하는데 '일반'의 일반(..)적인 영어 표현은 general이죠. raw와는 다소 거리가 멉니다.

(2) 스마트 포인터 이전의 포인터를 raw pointer라고도 부르지만 naked pointer라고도 불렀습니다. 왜냐면 스마트 포인터가 어떠한 포인터라도 그걸 "감싸는" 형태인데요, 그와 대비되는 아무 것에도 감싸지지 않은 날, 노출된 포인터라는 의미에서 raw/naked라는 단어가 쓰였다고 봅니다. 그래서 날/생/드러난 같은 단어가 raw에 영어 의미 뿐만 아니라 실제 구현 관점에서도 가장 근접하지 않나 생각합니다.

(3) "일반"의 반대를 생각해보면 "특수", special인데 스마트 포인터가 특수라고 생각하지 않습니다. 그냥 포인터 전체 집합이 있는데 이들을 쓰기 쉽도록 만든 것이 스마트 포인터라서 일반/특수라는 단어는 포인터 전체 집합에서 둘을 나누는 느낌이 듭니다.

**Comment by utilForever** [comment]
음, 생각해 보니 "날" 포인터라는 단어를 많이 보지 못해서 오는 거부감이 컸던 거 같습니다.
raw를 말 그대로 살리자면 일반이 아니겠죠. 일반은 우리가 보통 general이라는 단어를 사용하니까요.
스마트 포인터는 기존에 있던 포인터를 wrapping한 것이니 기존의 포인터가 위험에 노출되었다고 볼 수도 있다고 생각합니다. "날"보다 더 좋은 표현이 있다면 좋겠지만, 떠오르는 다른 단어가 없네요.

**Comment by minjang** [comment]
만약 '날'에 대한 거부감이 익숙치 않다, 순우리말이다, 라면 큰 걱정 안 해도 된다고 봅니다. 영어에서도 raw pointer가 그리 흔히 쓰이는 단어가 아니니깐요.

사실 그냥 젤 속편한 번역은 "스마트 포인터"처럼 raw를 그냥 우리 영어 발음으로 바꾸면 되는데, 제가 말씀드렸듯이 raw를 원래 한국어에서도 바로 영어로 쓰는 일이 거의 없었죠. 한다고 하더라도 law, low와 너무 헷갈리게 될 것이고요..

**Comment by utilForever** [comment]
'raw'라는 단어를 영어 발음으로 바꾸기엔 너무 혼동되는 단어가 많아서 저도 헷갈릴 수 있다고 생각합니다.

**Comment by naxxster** [comment]
개인적으로 번역 과정에서 영어에 대한 매핑이 이루어져야한다는 것에는 반대하는 입장입니다.
번역은 그 말을 보고 원문을 유추하기 위한 장치라기 보다는 원문을 모르는 사람이라도 그 말의 의미를 잘 이해할 수 있도록 하는데 목적이 있는 것일테니까요.

어떠한 단어가 영어의 raw 에 잘 매핑되나 보다는, 어떠한 단어를 썼을 때 raw pointer 가 담고 있는 의미를 한글로 잘 표현할 수 있느냐를 고민하는 것이 더 옳다는 생각입니다.

그런 의미에서 날 포인터라는말 자체로 의미를 잘 전달하느냐를 고민해봤으면 합니다.

**Comment by jenix21** [comment]
@naxxster 님 의견에 동의 합니다.
smart pointer 와 대비해서 강조하기 위해 raw 란 단어로 수식 했다고 생각 하구요.
번역된 문장안에서 raw pointer 와 smart pointer 잘 대비해서 표현 하면 어떨까 합니다.
그냥 raw 를 번역 안하는게 나을 수 도 있을 것 같구요.

**Comment by jenix21** [comment]
Effective Modern C++ 번역판엔 "생 포인터" 로 했네요! - -

**Comment by utilForever** [comment]
생 포인터, 날 포인터... 우리가 평소에 쓰지 않았던 단어라 그런지 생소하게 들리긴 하네요.
책에서도 서로 다른 표현으로 갈리는 말인데, 그만큼 확 와닿는 단어가 없다는 소리기도 하겠죠.

**Comment by blackscomber** [comment]
row pointers 로 쓰고 용어정리 부분을 둬서 주석으로 달아두면 어떨까요? C++11 이전 사용자나 이후 사용자는 단어만 봐서는 뜻이 와 닿지 않을거 같아요..;;
