### ISSUE TITLE
[질문] 최신 버전의 문서는 어떻게 업데이트 하나요?

### ISSUE THREAD

**Issue by jongheeyun** [CppKorea/CppCoreGuidelines#99]
안녕하세요.

1차 번역까지 작업하고 회사일이 밀려서 한참 못 보다가 이제야 다시 왔습니다. ^^;;

업데이트 된 원문은 어떻게 기존 번역작업과 머지해야 하나요?
최신 원문과 1차 작업한 내용이 많이 바뀌었습니다. 한줄 한줄 찾아서 붙여 넣기에는 무리인것 같습니다.
지금 생각으로는 원문을 통째로 가져와서 기존에 작업한 내용을 참고하여 다시 번역하는게 빠르지 않을까합니다. ^^; 좀 무식한 방법입니다.

스마~트한 방법있으면 공유해 주세요 ^^

**Comment by luncliff** [comment]
저는 일단 다시 재번역 하는 것으로 방향을 잡고 진행 중입니다.
다행히 크게 변경된 부분은 없지만 참고사항이(Note) 바뀐다던가 같이보기(See also)가 추가된 경우가 종종 있어서 대조작업을 할 수 밖에 없더군요.... :(

**Comment by jongheeyun** [comment]
@luncliff 최신원문을 가져와서 _재번역_하는게 시간이 더 걸릴지 덜 걸리지 모르지만 간단하고 정확하겠네요. ^^
